name: TechLove
favicon: null
layout_spectrum: 0.12873864569701254
typography_spectrum: 0.34339582500979304
title: For the Love of Tech
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.24514322937466204
  lightness: 0.8324845714960247
  saturation: 0.5692427563481033
  rhythmicContrast: 0.4301615795120597
purpose: []
